/**
 * Frontend API client.
 * 
 * Fetches data from the static JSON API generated by the backend's
 * export-static-api.mjs script. Campus-level files are fetched once
 * and filtered client-side for instant interactivity.
 */

// In-memory cache for campus group data (avoids re-fetching)
const groupCache: Record<string, Record<string, GroupRecord[]>> = {};

interface GroupRecord {
  group: string;
  day_time: string;
  mode: string;
  status: string;
  room: string;
  program: string;
  faculty: string;
}

export async function getCampus() {
  const res = await fetch("/api/campuses.json");
  if (!res.ok) throw new Error("Failed to fetch campus list");
  const data: { id: string; text: string }[] = await res.json();
  return data.filter((c) => c.id !== "X");
}

export async function getFaculty() {
  return [];
}

export async function getSubject(campus: string, _faculty: string) {
  if (!campus) return [];

  const res = await fetch(`/api/courses/${campus}.json`);
  if (!res.ok) throw new Error(`Failed to fetch courses for ${campus}`);

  const data: { code: string; path: string }[] = await res.json();
  return data.map((c) => ({ course: c.code, href: c.path }));
}

export async function getGroup(campus: string, _faculty: string, subject: string) {
  if (!campus || !subject) return [];

  // Fetch the entire campus group file once, then filter by course code
  if (!groupCache[campus]) {
    const res = await fetch(`/api/groups/${campus}.json`);
    if (!res.ok) throw new Error(`Failed to fetch groups for campus ${campus}`);
    groupCache[campus] = await res.json();
  }

  const groups = groupCache[campus][subject] || [];

  return groups.map((cls, idx) => ({
    no: `${idx + 1}.`,
    day_time: cls.day_time,
    class_code: cls.group,
    mode: cls.mode,
    attempt: cls.status,
    venue: cls.room,
    subject_code: subject,
    faculty: cls.faculty,
    subject_name: subject,
  }));
}

export async function getTimetable(matricNumber: string) {
  const res = await fetch(`/api/getTimetable`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ matricNumber }),
  });
  if (!res.ok) throw new Error("Failed to fetch timetable");
  return res.json();
}
